apiVersion: v1
kind: Service
metadata:
  name: front-nginx
spec:
  selector:
    app: my-app
    tier: front-nginx
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  type: LoadBalancer
...
---
apiVersion: v1
kind: Service
metadata:
  name: front-python
spec:
  selector:
    app: my-app
    tier: front-python
  ports:
  - protocol: TCP
    port: 5000
...
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: my-app
    tier: backend
  ports:
  - protocol: TCP
    port: 5000
...

