version: '3'
services:
  front:
    image: nginx
    volumes:
    - ./front/nginx-front.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      net:
        ipv4_address: 192.168.240.2
  front_python:
    build: ./front
    volumes:
    - ./front/app:/app
    working_dir: /app
    networks:
      net:
        ipv4_address: 192.168.240.3    
  back:  
    build: ./back
    volumes:
    - ./back/app:/app
    working_dir: /app
    networks:
      net:
        ipv4_address: 192.168.240.4
networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.240.0/24
